version: "3"
services:
  react-app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    env_file:
      - ./.env.production